// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8oeMLcscASUHJ7vzb_GBUIEy0h0GOKQw',
    appId: '1:235397945333:web:3fe819297b7c4ef83532bc',
    messagingSenderId: '235397945333',
    projectId: 'graduatioproject-36452',
    authDomain: 'graduatioproject-36452.firebaseapp.com',
    storageBucket: 'graduatioproject-36452.firebasestorage.app',
    measurementId: 'G-GPZ5FDH4PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3Z2Z7lb3YzL5JnFQQlnkJRJeAO1aSG4',
    appId: '1:235397945333:android:d99dcf78f8ba103f3532bc',
    messagingSenderId: '235397945333',
    projectId: 'graduatioproject-36452',
    storageBucket: 'graduatioproject-36452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHNZQIVhspKILM3ybTZ3NhJhEoan-dxHw',
    appId: '1:235397945333:ios:1b759e0b840286113532bc',
    messagingSenderId: '235397945333',
    projectId: 'graduatioproject-36452',
    storageBucket: 'graduatioproject-36452.firebasestorage.app',
    iosClientId: '235397945333-r5pg73de9dnc0cjdo6bppknsjg0kpbc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduatioProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHNZQIVhspKILM3ybTZ3NhJhEoan-dxHw',
    appId: '1:235397945333:ios:1b759e0b840286113532bc',
    messagingSenderId: '235397945333',
    projectId: 'graduatioproject-36452',
    storageBucket: 'graduatioproject-36452.firebasestorage.app',
    iosClientId: '235397945333-r5pg73de9dnc0cjdo6bppknsjg0kpbc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduatioProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8oeMLcscASUHJ7vzb_GBUIEy0h0GOKQw',
    appId: '1:235397945333:web:58248f5b893785393532bc',
    messagingSenderId: '235397945333',
    projectId: 'graduatioproject-36452',
    authDomain: 'graduatioproject-36452.firebaseapp.com',
    storageBucket: 'graduatioproject-36452.firebasestorage.app',
    measurementId: 'G-4SM8GNT6WL',
  );
}
